### ISSUE TITLE
Statistics endpoint

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-db#107]
We need to create a statistics api endpoint supplying the following stasts:

* Modes
  * name, count, link (unpopulated)
* Bands
  * name, count
* Total count of satellites
* Total count of transmitters
* Percentage of alive transmitters

For Bands the following lookup should be used:
<30.000.000 - HF 
30.000.000 ~ 300.000.000 - VHF
300.000.000 ~ 1.000.000.000 - UHF
1G ~ 2G - L
2G ~ 4G - S
4G ~ 8G - C
8G ~ 12G - X
12G ~ 18G - Ku
18G ~ 27G - K
27G ~ 40G - Ka

**Comment by comzeradd** [comment]
This is no [live on stage](https://db-dev.satnogs.org/stats/)l. Moving this to [relevant card](https://github.com/satnogs/satnogs-db/projects/1) and leaving it open till we push to production.

**Comment by comzeradd** [comment]
Deployed at [0.8](https://github.com/satnogs/satnogs-db/releases/tag/0.8).
