### ISSUE TITLE
Track "dead" satellites

### ISSUE THREAD

**Issue by comzeradd** [satnogs/satnogs-db#129]
It seems that [BY70](https://db.satnogs.org/satellite/41909/) re-entered the atmosphere.

I think it makes sense to keep dead satellites on DB for historical purposes. We should think how we could visualize that and if we should keep them on Network too.

**Comment by cshields** [comment]
it might make sense to have multiple status options.  I would consider "dead" to mean still in orbit but disfunctional. For BY70-1, "re-entered" might be more appropriate  (same functional connotation as dead but there is a difference in that it is no longer a trackable object). Dead objects could still be fed to apps like gpredict for people who want to look for signs of life, while re-entered objects could be left out.

**Comment by comzeradd** [comment]
Yes, good point. In a nutshell:

* Add a `status` field with predefined options: Alive, Dead, Re-Entered.
* Expose this information on the UI

Once this is done, we could exclude Dead & Re-Entered satellites from Network's observation functions. Specifically for Re-Entered we should probably stop trying to fetch TLEs. Is my assumption correct that the norad id is permanent for a satellite regardless of its state? Or re-entered satellite norad IDs are being re-used at some point?
