### ISSUE TITLE
Frequency display issue

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-db#139]
Might be due to rounding or other calculation?
e.g. https://db.satnogs.org/satellite/24278/

![screenshot from 2017-02-27 01-07-38](https://cloud.githubusercontent.com/assets/498592/23344676/260478f8-fc89-11e6-8d19-fe1344d3aaab.png)

**Comment by csete** [comment]
Note that when the same data ends up in Gpredict it looks fine.

**Comment by comzeradd** [comment]
Fixed at 51e985119e3b62df69f806426b928053ddbac9d7
