### ISSUE TITLE
Create tag for Frequency values

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-db#16]
Although in our database frequency values should be stored in Hz integers we need a beautified way to display those in our UI. A custom tag in Django templates would be a solution to be able to wrap values and return this: 434.450 MHz from this 434450000 .

Specs: MHz values before delimiter (".") and 3 digits after that. If necessary (!=0) values down to Hz would be displayed (like 144.500100 Hz) although we don't expect that to be anywhere near frequent need. In all cases trailing "MHz" should be present.

**Comment by ppapadeas** [comment]
https://github.com/satnogs/satnogs-network/blob/dev/network/base/templatetags/tags.py Is the exact same implementation in Network

**Comment by ppapadeas** [comment]
@comzeradd how would input (suggestions) be affected by this? Would we still require people to enter Hz values?

**Comment by comzeradd** [comment]
I'd suggest we use a custom filter to have a friendly output on the suggestion view.
On the suggestion form we go either way. Display Hz and expect Hz or display MHz and expect a float.
