### ISSUE TITLE
Missing modes

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-db#39]
Missing options for BPSK, PSK, MSK (GMSK is already there, slightly different), FFSK, PSK31 (the new PSat is testing this)

**Comment by ppapadeas** [comment]
r+ please proceed :)

**Comment by comzeradd** [comment]
I'm thinking of moving MODES to a new table, instead of hardcoded choices. This will allow us to expose them on the API and have the network sync them too.

**Comment by ppapadeas** [comment]
Good call @comzeradd , please go ahead as this will enable us to be more flexible. (like tracking if we can decode a mode or not with a flag etc)
