### ISSUE TITLE
Satellite suggestions don't appear on MacOS Safari when typing sat name

### ISSUE THREAD

**Issue by jeff-luszcz** [satnogs/satnogs-db#41]
On MacOS Safari (MacOs v10.9.5 and Safari v7.1.7) no suggestions appear when typing in the satellite search field.

Steps to reproduce:
Go to https://db.satnogs.org using MacOS Safari
start typing "Cube"
Notice that no suggestions appear.

Same process followed on MacOS Firefox and suggestions appear as expected

**Comment by cshields** [comment]
Same behavior on iOS WebKit browsers (meaning all of them)

In addition the search box does not "search" like one would expect... It seems to assume that the user would pick from one of the pop up options. This means that db just won't work at all in iOS. (For example enter "NO-84", it does not find anything even though there is such an entry in the db)

**Comment by ppapadeas** [comment]
Confirmed on MacOS Safari here too. @comzeradd should look into that, thanks for reporting!

**Comment by comzeradd** [comment]
That's a known issue. Safari's HTML5 support is poor, and in our case it totally lacks support for the [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) element.

**Comment by comzeradd** [comment]
The new UI introduced at #44 solves all these problems, since we no longer use datalist element for autocomplete.
