### ISSUE TITLE
unable to scroll in the dropdown on the satellite search box on the main page in Chrome/Chromium

### ISSUE THREAD

**Issue by elkos** [satnogs/satnogs-db#42]
Reported in Chrome 44.0.2403.89 (64-bit) https://www.reddit.com/r/amateurradio/comments/3em969/open_satellite_transmitter_database_opens_up_for/cthc1m0
Replicated in Chromium 43.0.2357.130 (64-bit)

**Comment by comzeradd** [comment]
There is a [Chromium bug](https://code.google.com/p/chromium/issues/detail?id=375637) tracking this. It seems that scrolling is not working at the moment for datalist in Chromium.

**Comment by comzeradd** [comment]
The new UI introduced at #44 solves all these problems, since we no longer use datalist element for autocomplete.
