### ISSUE TITLE
User Accounts?

### ISSUE THREAD

**Issue by KR0SIV** [satnogs/satnogs-db#6]
Unable to login, register accounts, or really do anything with this in regards to users.
It seems the official site is this way as well, has this portion not yet been completed?

**Comment by johngian** [comment]
Hey @KR0SIV 

This was a first take on ``satnogs-db`` using technologies like ``couchdb`` and ``angular`` that didn't really work out. @comzeradd is starting a new iteration based on python.

**Comment by comzeradd** [comment]
We'll probably keep Angular on the frontend and use python to implement the serializers for our data on the backend.

@KR0SIV Keep watching the project for code updates :)
