### ISSUE TITLE
Frequency detail is lacking

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-db#86]
In the user interface of the DB, frequencies are cut off at the khz level when there may be an offset down at the hz level.

For instance, the tlm frequency for bisonsat below:

https://db.satnogs.org/satellite/40968/

Shows as 437.375 Mhz when in reality it is set to 437375500.  Thankfully the frequency is in the db correctly at that granular level for satnogs purposes, but someone referring to the frequency for other purposes might be thrown off a bit.

I would suggest we stick to displaying at the Khz granularity except when it does not land at a 000 hz.

**Comment by comzeradd** [comment]
I 'd rather we have a unified way of displaying frequencies. So we should either display everything in Khz or keep the Mhz and add a tooltip showing the frequency in Hz.

**Comment by mistermatt2u** [comment]
@comzeradd Can you clarify the position on this? I think this issue also affects the transponder entry for [INMARSAT-4 F1](https://db.satnogs.org/satellite/28628/). Actual freq. is 1525.9525; but the web UI rounded up to 1525.953. Slightly different problem; but maybe the same discussion of fix.

**Comment by comzeradd** [comment]
I opened a PR. I increased precision for all frequencies and added a tooltip with the full Hz value.

![hz](https://cloud.githubusercontent.com/assets/939357/20187008/153d04ee-a77b-11e6-88bd-9ecaa0515eca.png)

**Comment by mistermatt2u** [comment]
@comzeradd I read the PR comments. It looks good to me. For UHF/VHF satellites, I don't foresee that last 500 Hz coming into play often. For HF and higher than UHF, it seems to be more common. Having the 5 subscript seems to be a good solution. It prevents rounding, which makes the listed frequency more accurate. Tooltip looks nice too.

**Comment by comzeradd** [comment]
This is now live on stage. Here is an [example](https://db-dev.satnogs.org/satellite/40968/).

I'll leave this open till we deploy on production.

**Comment by comzeradd** [comment]
Deployed at [0.8](https://github.com/satnogs/satnogs-db/releases/tag/0.8).
