### ISSUE TITLE
Telemetry visualisation

### ISSUE THREAD

**Issue by keikreutler** [satnogs/satnogs-db#88]
Based on sample data taxonomy from discussion on issue #84 and schema on Discourse https://community.satnogs.org/t/proposed-schema-and-data-flow-for-telemetry/638

**Comment by keikreutler** [comment]
Updates on https://github.com/satnogs/satnogs-db/tree/telemetry

**Comment by comzeradd** [comment]
Deployed at [0.8](https://github.com/satnogs/satnogs-db/releases/tag/0.8).
